### ISSUE TITLE
Reg dimension of the bar magnets for B645 arrangement

### ISSUE THREAD

**Issue by abanerjee123** [ARTS-Laboratory/Compact-NMR#1]
<img width="372" alt="Polarization_Plot" src="https://github.com/user-attachments/assets/cb0ff086-5020-4a8a-9008-f54d9a2eab2d">
Hi
       I am interested to make a small magnet for a desktop NMR system. I am interested in the 10 magnet arrangement. Could you share the dimension of the 10 magnets used in the B645 arrangement? 

Thanks 
Abhishek

file:///home/abhishek/FPGA_devel/Compact-NMR-master/System_development/magnet_design/B645_Tesla_magnet/media/Polarization_Plot.PNG

**Comment by austindowney** [comment]
Of course, the magnet part numbers are "BX8X88" and "BX844" from KJ Magnets.
